spring:
  application:
    name: nexuspay-transaction-worker
  datasource:
    url: jdbc:postgresql://localhost:5433/nexuspay
    username: nexuspay
    password: nexuspay
  cloud:
    aws:
      region:
        static: us-east-1

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

nexuspay:
  aws:
    profile: nexuspay-worker
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/797771596673/api-processar-transferencia-worker.fifo
